include(${CMAKE_CURRENT_LIST_DIR}/Dependencies.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Files.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Project.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Properties.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Utils.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Version.cmake)
